DROP TABLE IF EXISTS user_auth CASCADE;

CREATE TABLE user_auth (
    username varchar(250) NOT NULL PRIMARY KEY UNIQUE,
    user_id integer REFERENCES users(user_id) ON DELETE CASCADE,
    password varchar(250) NOT NULL,
    disabled boolean DEFAULT false
);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('admin',1,'password',false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('supervisor',2,'password',false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('crew',3,'password',false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('horrocks', 25, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('morris', 26, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('muller', 27, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('rose', 28, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('ross', 29, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('thoennes', 30, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('evans', 31, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('green', 32, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('quesenberry, a', 33, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('ryan', 34, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('tally', 35, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('baunsgard', 36, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('allenton', 38, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('capristo', 39, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('villanueva, r', 40, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('fair', 41, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('vosel', 42, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('robertson', 43, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('spaulding', 44, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('doran', 45, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('meyer', 46, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('leffler, s.', 47, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('irizarry', 48, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('gordon', 49, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('rankin, h', 50, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('coppinger', 51, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('beresford', 52, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('riedl', 53, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('vogel', 54, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('huchingson', 55, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('popa', 56, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('hynes', 58, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('kulp', 59, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('firestone', 60, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('chesley', 61, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('cruz', 62, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('hampton', 63, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('blomquist', 64, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('white', 65, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('swim', 66, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('nash', 67, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('jacques', 68, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('denton', 69, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('rowsell', 70, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('dungan', 71, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('wood, d', 72, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('skarlatos', 73, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('hughes', 74, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('shoemaker', 75, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('smith, k', 76, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('johnson, c', 77, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('miller', 78, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('cooper', 79, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('layton', 80, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('holmes', 81, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('mayers', 82, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('bradley', 83, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('friedman', 84, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('pettersen', 85, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('brockman', 86, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('oberkrom', 87, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('stine', 88, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('villanueva, e', 89, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('smith, t', 90, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('stephens', 91, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('fleet', 92, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('ayers', 93, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('bienenfeld', 94, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('mundell', 95, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('robinson', 96, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('van de rostyne', 97, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('bissette', 98, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('yergin, m', 99, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('hughey', 100, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('wood', 101, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('blomquist, k', 102, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('slifer', 103, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('limones', 104, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('wolfe', 105, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('ritacco', 106, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('lucas', 107, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('koenig', 108, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('weaver', 109, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('heldreth', 110, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('maxwell', 111, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('allen', 112, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('adolphin', 113, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('martini', 114, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('zehr', 115, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('hawkins', 116, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('yates', 117, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('reimer', 118, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('krueger', 119, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('bochniak', 120, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('harpe', 121, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('kirby', 122, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('lang', 123, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('lathrop', 124, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('martin', 125, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('thompson', 126, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('beverly', 127, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('chapman', 128, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('markin', 129, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('pinto', 130, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('staszek', 131, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('wyatt', 132, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('detloff', 133, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('villanueva, b', 134, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('nguyen', 135, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('smith', 136, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('ferguson', 137, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('decremer', 138, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('brosius', 139, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('brown', 140, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('snyder', 141, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('dawson', 142, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('rankin, l', 143, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('leffler, a.', 144, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('schaefer', 145, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('yergin', 146, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('peery', 147, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('modjtabai', 148, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('bickford', 149, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('williams', 150, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('holmgren', 151, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('bassett', 152, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('swanson', 153, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('bizzell', 154, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('cereno', 155, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('young', 156, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('lake', 157, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('ly', 158, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('zimmerman', 159, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('davis, b', 160, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('hastings', 161, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('gutierrez', 162, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('ngo', 163, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('geroux', 164, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('bolo', 166, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('jensen', 167, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('reilly', 168, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('schultz', 169, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('milton', 170, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('larkin', 171, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('bykov', 172, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('bergren', 173, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('brodd', 174, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('bruce', 176, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('camel', 177, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('dalrymple', 178, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('davis', 179, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('fawcett', 180, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('mayer', 181, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('royster', 182, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('thiessen', 183, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('calder', 184, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('holmgren, a', 186, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('treichler', 187, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('warren', 188, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('yamada', 189, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('roberts', 190, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('farmer', 191, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('burton', 192, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('schwertman', 193, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('olson', 195, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('jugo', 196, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('trausch', 197, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('carey', 198, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('pierce', 199, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('thomson', 200, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('blevins', 201, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('hutcheson', 202, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('knutsen', 203, 'password', false);
INSERT INTO user_auth (username, user_id, password, disabled) VALUES ('charles', 1, 'password', false);